### ISSUE TITLE
window.navigator.onLine

### ISSUE THREAD

**Issue by mgsstms** [neoziro/angular-offline#1]
Greg,

The window.navigator.onLine attribute and its associated events are currently unreliable on certain web browsers:
http://stackoverflow.com/questions/3181080/how-to-detect-online-offline-event-cross-browser
http://louisremi.com/2011/04/22/navigator-online-alternative-serverreachable/ instead of ajax

Of coz, usage offline.js is the best alternative at the moment. To avoid this dependency the simple ping of the server (as alternative to window.navigator.onLine) could be done. For example, such code

	$rootScope.isSendCheckConnection = false;
	$rootScope.interval = 10; //seconds
	$rootScope.testPath = 'images/pixel.jpg';

	var checkConnection = function () {
		//http interceptor is invoked during these calls, I wanted to avoid that, hence I had used $.ajax for the calls
		if ($rootScope.isSendCheckConnection) {
			$.ajax({
				type: "HEAD",
				url: ($rootScope.testPath ? $rootScope.testPath : document.location.pathname) + "?rand=" + Math.floor((1 + Math.random()) * 0x10000),
				contentType: "application/json",
				error: function () {
					$rootScope.isOnline = false;
				},
				success: function (data, textStatus, xhr) {
					var status = xhr.status;
					$rootScope.isOnline = status >= 200 && status < 300 || status === 304;
				}
			});
		} else {
			$rootScope.isOnline = connectionStatus.isOnline();
		}
	};

	$rootScope.isOnline = true;
	$interval(checkConnection, $rootScope.interval * 1000);

	$rootScope.$watch('isOnline', function (newVal) {
//		console.log("isOnline: ", newVal, moment());
		//custom logic here
		if ($rootScope.isSendCheckConnection) {
			connectionStatus.online = newVal;
		}
	});

could be integrated into this.isOnline function

p.s.Of coz, jQuery's ajax could be replaced with XMLHttpRequest

**Comment by jpike88** [comment]
Not only this, but it doesn't listen to cellular connections.

To the owner of this repo: You should put in bold capital letters that this is the case, as that makes it next to useless for modern apps.

**Comment by neoziro** [comment]
I agree that `navigator.onLine` is not correctly implemented in all browser, you can use this module if you want a basic offline support, it's probably not the best option if you target a full offline support.
