### ISSUE TITLE
connectionStatus IS USELESS! DO NOT USE IT!

### ISSUE THREAD

**Issue by jpike88** [neoziro/angular-offline#2]
I wonder why it was even implemented, if you look at navigator.onLine you'll notice it only checks to see if the device is connected to a LAN (aka utterly useless).

**DO NOT USE connectionStatus is your app is going to be used by mobiles/tablets with cellular data.**

This should be in big letters at the top of the readme.

**Comment by neoziro** [comment]
Yes I agree, it depends of the navigator implementation, but it's cheap and it's true most of time.
